# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = 'bento/ubuntu-14.04'

  config.vm.provision 'shell', inline: <<-SHELL
    sudo bash
    apt-get update
    apt-get install -y curl
    curl -L https://www.opscode.com/chef/install.sh | sudo bash -s -- -v 11.18.12
    export PATH="/opt/chef/embedded/bin/:$PATH"
    gem install chef-sugar --no-rdoc --no-ri
    export BUSSER_ROOT="/opt/busser"
    export GEM_HOME="/opt/busser/gems"
    export GEM_PATH="/opt/busser/gems"
    export GEM_CACHE="/opt/busser/gems/cache"
    /opt/chef/embedded/bin/gem install busser --no-rdoc --no-ri
    /opt/chef/embedded/bin/gem install serverspec --no-rdoc --no-ri
    /opt/busser/gems/bin/busser setup
    /opt/busser/gems/bin/busser plugin install busser-serverspec
  SHELL
end
